### ISSUE TITLE
Missing Camera Parameters in SimRGBD-Franka Dataset

### ISSUE THREAD

**Issue by KJZhuAutomatic** [Nimolty/RoboKeyGen#2]
Thank you for your great work!

I would like to use the SimRGBD-Franka simulation dataset you have provided. However, I couldn't find the camera parameter file. The _camera_settings.json file appears to be empty. Could you please let me know if I missed something?

Thank you again for your contributions!

**Comment by Nimolty** [comment]
Dear KJZhuAutomatic,
    The camera intrinsics for the SimRGBD-Franka simulation dataset RGB, Depth, Mask, IR images are [[502.30, 0.0, 319.5], [0.0, 502.30, 179.5], [0.0, 0.0, 1.0]]. The camera extrinsics are saved in the meta jsons.

**Comment by KJZhuAutomatic** [comment]
Thank you so much for the quick response and for providing the camera intrinsics and extrinsics! I really appreciate your help.
